// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Rates an outfit provided as a photo, giving it a score out of 10.
 *
 * - rateOutfit - A function that handles the outfit rating process.
 * - RateOutfitInput - The input type for the rateOutfit function.
 * - RateOutfitOutput - The return type for the rateOutfit function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RateOutfitInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the outfit, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type RateOutfitInput = z.infer<typeof RateOutfitInputSchema>;

const RateOutfitOutputSchema = z.object({
  rating: z
    .number()
    .describe('The outfit rating, out of 10.')
    .min(0)
    .max(10),
  suggestions: z
    .string()
    .describe('Suggestions to improve the outfit, in terms of color and look.'),
});
export type RateOutfitOutput = z.infer<typeof RateOutfitOutputSchema>;

export async function rateOutfit(input: RateOutfitInput): Promise<RateOutfitOutput> {
  return rateOutfitFlow(input);
}

const prompt = ai.definePrompt({
  name: 'rateOutfitPrompt',
  input: {schema: RateOutfitInputSchema},
  output: {schema: RateOutfitOutputSchema},
  prompt: `You are a fashion expert. Rate the outfit in the photo out of 10, and suggest improvements to the color and look.

  Photo: {{media url=photoDataUri}}
  `,
});

const rateOutfitFlow = ai.defineFlow(
  {
    name: 'rateOutfitFlow',
    inputSchema: RateOutfitInputSchema,
    outputSchema: RateOutfitOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
